name: PacketWhitelistNbt
version: ${project.version}
main: xuan.cat.packetwhitelistnbt.code.Index
api-version: 1.13
depend: [ProtocolLib]
authors: [xuancat0208]

commands:
  whitelistnbt:
    usage: true
